### PR TITLE
Changed _keyExtractor function to fix #51

### LINKED ISSUE #51: [VirtualizedList] - Warning: Each child in an array or iterator should have a unique "key" prop.
Hello,
there is a warning in render method of VirtualizedList. Not sure if this is your problem... I wasn't able to find it in code yet. It may be a problem of one of the dependencies... Can you please look at it?
It's only a warning, but still... :)

`
Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `VirtualizedList`. See https://fb.me/react-warning-keys for more information.
    in CellRenderer (at VirtualizedList.js:463)
    in VirtualizedList (at FlatList.js:557)
    in FlatList (at Column.js:129)
    in RCTView (at View.js:113)
    in View (at Column.js:121)
    in Column (at Masonry.js:118)
    in StaticRenderer (at ListView.js:464)
    in RCTScrollContentView (at ScrollView.js:707)
    in RCTScrollView (at ScrollView.js:800)
    in ScrollView (at ListView.js:332)
    in ListView (at Masonry.js:113)
    in RCTView (at View.js:113)
    in View (at Masonry.js:112)
    in Masonry (at PageGallery.js:13)
    in PageGallery (at App.js:203)
    in RCTScrollContentView (at ScrollView.js:707)
    in RCTScrollView (at ScrollView.js:800)
    in ScrollView (at KeyboardAwareScrollView.js:27)
    in KeyboardAwareScrollView (at Content.js:10)
    in Content (at connectStyle.js:384)
    in Styled(Content) (at App.js:302)
    in RCTView (at View.js:113)
    in View (at Container.js:19)
    in Container (at connectStyle.js:384)
    in Styled(Container) (at App.js:252)
    in RCTView (at View.js:113)
    in View (at index.js:570)
    in RCTView (at View.js:113)
    in View (at index.js:557)
    in Drawer (at index.js:10)
    in Drawer (at App.js:234)
    in RCTView (at View.js:113)
    in View (at Root.js:14)
    in Root (at connectStyle.js:384)
    in Styled(Root) (at App.js:233)
    in App (at registerRootComponent.js:36)
    in RootErrorBoundary (at registerRootComponent.js:35)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:100)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:121)
    in AppContainer (at renderApplication.js:34)
`

### PR DESCRIPTION
**Pull request by soukupl**
Changed _keyExtractor function to build item key from image 'uri' and optional 'key' value. Fixing issue #51 .

### CODE REVIEW

**Comment by brh55** [comment]
@soukupl 
Looks like an undefined reference breaking the test. `.data` is an optional property so referencing `data.key` is causing the issue within column.js

**Comment by soukupl** [comment]
@brh55 hmmm... so maybe moving the key from data to main item as it is with uri? item.data.rui is moved somewhere to item.uri, so I can make this move at the same spot to fix the test issue :)

**Comment by brh55** [comment]
@soukupl sounds good to me, it seems more of a property of the item rather then meta data 👍.

**Comment by brh55** [comment]
@soukupl Did you end up figuring this out? Let me know if you need some assistance 👍

**Comment by soukupl** [comment]
@brh55 sorry... was busy :) I will work on it later today and will update or create a new pull request with new code :)

**Comment by brh55** [comment]
@soukupl actually it looks like just the snapshot is failing, ill need to reset the snapshot and push

**Comment by brh55** [comment]
woops, looked like a minor change I had to update to the brick instead of the data object. Everything  is good now 👍

**Comment by soukupl** [comment]
@brh55 sorry... we were out for holidays and I was quite busy days before leaving and didn't find a time to "work" on this :)

but I'm glad that it is now resolved :D

**Pull request merged**
