### PR TITLE
Order image rendering

### PR DESCRIPTION
**Pull request by kmcgill88**
Per #30 I've added the ability to order images based on their index of the `data` passed to Masonry. I could envision use cases for both ordered and non so I added the prop `sorted` to Masonry to give users the option to choose.

This may not be the *best* solution but it is *a* solution. 🥇

### CODE REVIEW

**Comment by kmcgill88** [comment]
@brh55 @srameshr I'm pretty new to the JS and RN world (native dev background) but I feel like I should add a test for this to confirm its sorted. I figured I'd throw this out for an early review.

**Comment by srameshr** [comment]
@brh55 Could you also add this in the docs?

**Comment by brh55** [comment]
@kmcgill88 Looks good to me! We could probably write a few simple test to check that the indexes are inserted, but other than very much dig it.

If you would want to assist in maintaining the repo, I would also add a maintainer section in the `readme` and add yourself to the list 👍 .

**Comment by kmcgill88** [comment]
@brh55 I'll try to add a few tests. If you wanna add me as a maintainer that's cool with me. I'll update the README and poke at adding test(s) and holler back.

@srameshr I did add the `sorted` prop to the README under the `Component Props` section. What else were you thinking? A full JSX example?

**Comment by srameshr** [comment]
As of now a prop in docs is fine. Il add the js example if you are busy.

**Comment by brh55** [comment]
We will also need to bump up version @kmcgill88 for npm. I feel this is more aligned with a bug fix, and should bump up the package.json to v0.2.2, unless you feel it's more of a functionality change. In that case, we can move this to v0.3.0, and set up a v0.4.0 branch. Thoughts, @kmcgill88 @srameshr ?

**Comment by kmcgill88** [comment]
@brh55 I sorta feel like this is a feature since you can optionally add the `sorted` prop now. This branch is good to go unless you feel changes need to be made. I'm going to try out your `0.3.0` performance improvement now.

**Comment by brh55** [comment]
Alrighty let's push this to v0.3.0 and we will merge over the performance updates once things are cleared.

**Pull request merged**
